import Header from '@/components/Header/page'
import './globals.css'
import { Roboto_Mono } from 'next/font/google'
import Footer from '@/components/Footer/page'

const robotomono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'SMP Cejera',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={robotomono.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
